### ISSUE TITLE
Update package name

### ISSUE THREAD

**Issue by mbestavros** [mbestavros/GeometricWeather#1]
Per @IzzySoft: "to avoid collision – cross-updates won't be possible anyway due to different signature"

**Comment by mbestavros** [comment]
@IzzySoft Question -- would a build variant, as detailed [here](https://developer.android.com/studio/build/application-id), be sufficient? I'm a little intimidated at the scope of the changes for a full package rename -- would likely make rebasing a whole lot harder.

**Comment by IzzySoft** [comment]
As long as you use `applicationId` and not `applicationIdSuffix`, yes. The latter has problems with F-Droid, AFAIR.

Further, if you only take care for removing the "bad stuff", just adding a suffix (again, better use `applicationId` and not `applicationIdSuffix` – or ask the F-Droid devs/packagers whether issues with the latter are meanwhile solved) might be fine. Otherwise something like

```gradle
applicationId "mbestavros.com.geometricweather"
```

might be better. Another problem [lies here](https://github.com/mbestavros/GeometricWeather/blob/d5f2701a0863cc33ad2c562d59eb0be172d8046f/app/build.gradle#L69): that repo is not listed with the [trusted maven repos](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L104) and thus won't be accepted. Maybe the freed version can do without it?

**Comment by mbestavros** [comment]
@IzzySoft Good thoughts, thanks for the pointers.

I'm having a hell of a time with the `applicationId`, though... the app crashes on open whenever it's changed from `wangdaye.com.geometricweather`. Any pointers?

**Comment by IzzySoft** [comment]
Sorry, I'm no dev, so I could only guess – and guide you completely off-road that way, so I better don't do that. Do the crashes also happen when using e.g. `wangdaye.com.geometricweather.foss` as `applicationId`? If not, I'd simply take the "easy approach" and use that.

**Comment by mbestavros** [comment]
@IzzySoft They do happen, unfortunately.

A full package rename _does_ work... but, like I said before, that might make forwarding changes from upstream kind of painful. Still, it's a possibility, so I'll consider it if nothing else works.

I'm going to keep hacking on it for now.

**Comment by mbestavros** [comment]
Never mind, I'm giving up :stuck_out_tongue: 

I think restructuring my commits to make the package change happen last will make rebasing as easy as I can hope for, so I'll do that. We still get the end result of a renamed package, so that should be fine.

**Comment by IzzySoft** [comment]
Maybe ask an experienced developer who has worked un forks like this? Or check with the developer community at StackOverflow? A good starting point for research would be [this search](https://stackoverflow.com/search?q=[android]+change+applicationId) (you can also [restrict it to answered questions](https://stackoverflow.com/search?q=[android]+change+applicationId+answers%3A1)).

**Comment by mbestavros** [comment]
Seems like I've been through every SO question on the topic :stuck_out_tongue: 

I've put out some feelers to see if there's a better way to approach it. If that doesn't yield fruit, a package rename is the way I'll go. Worst case, I have to do it again each release (but it's not that hard to begin with).

**Comment by IzzySoft** [comment]
Best luck! I know there must be a way as there are several "forked projects" still in touch with their "upstream".

**Comment by mbestavros** [comment]
@IzzySoft I gave it my best shot... the issues here are deeper than I'd like to address on my own. The app really depends on the package name and application ID being the same, and unraveling that isn't worth the time compared to the five-minute overhead per rebase a full package rename adds. It shouldn't impact my ability to deliver downstream releases.

**Comment by IzzySoft** [comment]
> The app really depends on the package name and application ID being the same

Well, I thought they both were synonyms :laughing: See, I'm no dev. Whatever is easiest for you. It should just be clearly distinguishable, including by the packageName. I don't care much whether that's done by the prefix (replacing `wangdayeeeeee` by `mbestavros`) or by simply adding a suffix (like `.noanal[ytics]` or `.foss`) – that's rather a philosophical question. Otherwise, if the packageName stays the same, users will have errors when "cross-updating" (signature mismatch), which would raise confusion.

**Comment by mbestavros** [comment]
@IzzySoft In an ideal world, I'd be able to just switch the app ID without complications -- that's how it's supposed to work, according to Google's documentation, and it'd appear as a separate app. However, Geometric Weather assumes the app ID and package name are identical in parts of its code, making that quick switch infeasible. The way I'm proposing will still net the end result we want: a separate package name.

I'm planning on just using `com.mbestavros.geometricweather` in place of `wangdaye.com.geometricweather`.
