### ISSUE TITLE
[Feature Request] Increase darkness of text

### ISSUE THREAD

**Issue by Oymate** [mbestavros/GeometricWeather#9]
For reference
https://play.google.com/store/apps/details?id=widget.dd.com.overdrop.free

**Comment by mbestavros** [comment]
@Oymate Hello, welcome! Thanks for the request.

I'll note that my fork is not really intended to have significant feature differences from the [original, upstream version](https://github.com/WangDaYeeeeee/GeometricWeather) -- rather, it's simply to offer a fully FOSS-compatible version of it. Since your request is related to design, I'd encourage you to open an issue upstream so the original developer can be aware. This will allow the change to be represented in all versions, FOSS or not.

Additionally, I'd encourage you to describe what you're looking for in a little greater detail. I notice you've linked to Overdrop, but you don't explain how that relates to your request or what a contributor could do to make things better. Just a friendly tip :)
